use crate::models::volcano::Volcano;

/// Returns a curated list of notable active volcanoes worldwide.
/// In a future iteration, this could fetch from the Smithsonian GVP RSS feed.
pub fn get_active_volcanoes() -> Vec<Volcano> {
    vec![
        Volcano {
            id: "kilauea".into(),
            name: "Kilauea".into(),
            latitude: 19.421,
            longitude: -155.287,
            status: "warning".into(),
            last_eruption: "2023-ongoing".into(),
            description: "Shield volcano, Hawaii".into(),
        },
        Volcano {
            id: "etna".into(),
            name: "Mount Etna".into(),
            latitude: 37.748,
            longitude: 14.999,
            status: "watch".into(),
            last_eruption: "2024".into(),
            description: "Stratovolcano, Sicily, Italy".into(),
        },
        Volcano {
            id: "stromboli".into(),
            name: "Stromboli".into(),
            latitude: 38.789,
            longitude: 15.213,
            status: "advisory".into(),
            last_eruption: "2024".into(),
            description: "Stratovolcano, Aeolian Islands, Italy".into(),
        },
        Volcano {
            id: "piton".into(),
            name: "Piton de la Fournaise".into(),
            latitude: -21.244,
            longitude: 55.708,
            status: "watch".into(),
            last_eruption: "2024".into(),
            description: "Shield volcano, Réunion Island".into(),
        },
        Volcano {
            id: "sakurajima".into(),
            name: "Sakurajima".into(),
            latitude: 31.585,
            longitude: 130.657,
            status: "warning".into(),
            last_eruption: "2024-ongoing".into(),
            description: "Stratovolcano, Kyushu, Japan".into(),
        },
        Volcano {
            id: "popocatepetl".into(),
            name: "Popocatépetl".into(),
            latitude: 19.023,
            longitude: -98.622,
            status: "warning".into(),
            last_eruption: "2024-ongoing".into(),
            description: "Stratovolcano, Mexico".into(),
        },
        Volcano {
            id: "merapi".into(),
            name: "Mount Merapi".into(),
            latitude: -7.541,
            longitude: 110.446,
            status: "watch".into(),
            last_eruption: "2024".into(),
            description: "Stratovolcano, Java, Indonesia".into(),
        },
        Volcano {
            id: "semeru".into(),
            name: "Semeru".into(),
            latitude: -8.108,
            longitude: 112.922,
            status: "watch".into(),
            last_eruption: "2024".into(),
            description: "Stratovolcano, Java, Indonesia".into(),
        },
        Volcano {
            id: "erebus".into(),
            name: "Mount Erebus".into(),
            latitude: -77.53,
            longitude: 167.17,
            status: "normal".into(),
            last_eruption: "Continuous".into(),
            description: "Stratovolcano, Antarctica".into(),
        },
        Volcano {
            id: "fuego".into(),
            name: "Volcán de Fuego".into(),
            latitude: 14.473,
            longitude: -90.88,
            status: "warning".into(),
            last_eruption: "2024-ongoing".into(),
            description: "Stratovolcano, Guatemala".into(),
        },
        Volcano {
            id: "taal".into(),
            name: "Taal".into(),
            latitude: 14.002,
            longitude: 120.993,
            status: "advisory".into(),
            last_eruption: "2022".into(),
            description: "Caldera, Luzon, Philippines".into(),
        },
        Volcano {
            id: "villarrica".into(),
            name: "Villarrica".into(),
            latitude: -39.42,
            longitude: -71.93,
            status: "advisory".into(),
            last_eruption: "2024".into(),
            description: "Stratovolcano, Chile".into(),
        },
        Volcano {
            id: "mauna_loa".into(),
            name: "Mauna Loa".into(),
            latitude: 19.475,
            longitude: -155.608,
            status: "normal".into(),
            last_eruption: "2022".into(),
            description: "Shield volcano, Hawaii".into(),
        },
        Volcano {
            id: "aso".into(),
            name: "Mount Aso".into(),
            latitude: 32.884,
            longitude: 131.104,
            status: "advisory".into(),
            last_eruption: "2024".into(),
            description: "Caldera, Kyushu, Japan".into(),
        },
        Volcano {
            id: "ruang".into(),
            name: "Ruang".into(),
            latitude: 2.30,
            longitude: 125.37,
            status: "warning".into(),
            last_eruption: "2024".into(),
            description: "Stratovolcano, Sulawesi, Indonesia".into(),
        },
    ]
}
